#!/bin/ksh
#
#  javax [args...] -- execute program just built by jcontx
#
#  assumes the class name is "a_out" in directory "./tmp"

JDIR=..
TMP=./tmp
JAVA="java"

export CLASSPATH=${CLASSPATH-.}:$JDIR/rts
cd $TMP
$JAVA a_out
