#!/bin/ksh
#
#  jcontx file.icn -- build and run an Icon program using the Jcon translator
#
#  assumes that the jcon "test" directory is the current directory
#  writes class files in ./tmp after deleting previously existing class files

TMP=./tmp

JCON="../src/jcon -O -target=java"
JAVAC="toba -K"
JAVA="java"

for FNAME; do
    BASE=${FNAME%.icn}
    FILES="$FILES $BASE.icn"
done

set -e
export CLASSPATH=${CLASSPATH-.}:../../rts

test -d $TMP || mkdir $TMP
$JCON $FILES >$TMP/a_out.java

cd $TMP
rm -f *.class 
$JAVAC a_out.java
$JAVA a_out

