#!/bin/ksh -p
#
#  jtoba -- compile program with jcont and toba
#
#  usage:  jtoba file.icn ...
#	writes	file.tx		(toba executable)
#
#  requires t11 (toba for Java 1.1) in search path
#  requires toba package of runtime system in ../bin/JCON

BASE=${1%.icn}

set -x
jcont -d "$@"
TOBAPATH=../bin/JCON t11 -o $BASE.tx jtmp/*.class
rm -rf jtmp $BASE $BASE.zip
