#!/bin/ksh
#
#  jxprof filename [args] -- execute Jcon program with profiling
#
#  creates filename.prof 

if [ $# = 0 ]; then
   echo "usage: $0 file [args]" 1>&2
   exit 1
fi

FNAME=$1
shift

DD=`sed -n <$FNAME '
    /^dd/s/ <.*//p
    /^exit/q
'` || exit 1

EXPORT=`sed -n <$FNAME '
    /^export/p
    /^exit/q
'` || exit 1

JAVA=`sed -n <$FNAME '
    /^[^ ]*java /s/ / -prof:'$FNAME.prof' /p
    /^exit/q
'` || exit 1

TZIP=/tmp/jcon$$.zip
trap "rm -rf $TZIP" 0 1 2 15

eval "$DD" <$FNAME >$TZIP 2>/dev/null
eval "$EXPORT"
eval "$JAVA"
