#!/bin/ksh
#
#  runtest [file...] -- run test

if [ $# = 0 ]; then
   set *.std
fi

for FNAME; do
    BASE=${FNAME%.*}
    echo ${BASE}:
    ./jcont -s $BASE -x >$BASE.out
    cmp $BASE.std $BASE.out
done
