#!/bin/ksh
#
#  runtest [file...] -- run test

if [ $# = 0 ]; then
   set *.std
fi

ERRORS=0

for FNAME; do
    BASE=${FNAME%.*}
    echo ${BASE}:
    ../bin/jcont -s $BASE
    if [ -r $BASE.dat ]; then
	./$BASE $BASE.dat <$BASE.dat >$BASE.out
    else
	./$BASE </dev/null >$BASE.out
    fi
    cmp $BASE.std $BASE.out || let 'ERRORS = ERRORS + 1'
done

case $ERRORS in
    0)  echo "Testing complete; no errors.";  exit 0;;
    1)  echo "Testing complete; ***** $ERRORS error. *****";  exit 1;;
    *)  echo "Testing complete; ***** $ERRORS errors. *****";  exit 1;;
esac
