#!/bin/ksh -p
#
#  kreport progname... -- report user CPU times and ratios

echo ''
uname -a
date
./version.ixe
./version.jxe
echo ''
echo JAVA_COMPILER=${JAVA_COMPILER-"<unset>"}
echo JAVA_FAST_JVM=${JAVA_FAST_JVM-"<unset>"}
java -version 2>&1
java -fullversion 2>&1
echo ''
echo '          icont  jcont    ratio'
for p; do
    echo `<$p.it` `<$p.jt` | awk '
	{ printf("%-8s %6.6f %6.6f %8.6f\n", "'$p'", $1, $4, $4 / $1); }
    '
done
echo ''
