#!/bin/ksh -p
#
#  jtoba -- compile program with jcont and toba
#  <<ARIZONA-ONLY>>
#
#  usage:  jtoba file.icn ...
#	writes	file.tx		(toba executable)
#

BASE=${1%.icn}

set -e
set -x
export TOBA=/cs/scout/build/pab/toba-1.1-12may98
export TPKG=$TOBA/packages
export PATH=$TOBA/bin:/cs/sumatra/linux/jdk1.1.3/bin:/bin:/usr/bin
export CLASSPATH=$TPKG/BISS/classes:$TPKG/SUNAPI/classes:..
export TOBAPATH=$TPKG/BISS:$TPKG/TOBA:$TPKG/SUNAPI:$TPKG/RUNTIME:../bin/JCON
../bin/jcont -d "$@"
toba -v -i -O -o $BASE.tx jtmp/*.class
rm -rf jtmp $BASE $BASE.zip
