#!/bin/sh
#
#  rtprof program args -- execute jtoba program with runtime system profiling
#  <<ARIZONA-ONLY>> (Solaris only)
#
#  stdout and stderr are directed to rtprof.out and rtprof.err

set -x
rm -f /var/tmp/libJCON.so.profile
LD_PROFILE=libJCON.so
export LD_PROFILE
"$@" >rtprof.out 2>rtprof.err
gprof ../bin/JCON/libJCON.so /var/tmp/libJCON.so.profile
