#!/bin/sh
#
#  az-install -- install revised documentation in www areas at Arizona
#
#  REMINDERS:
#	With each change, modify date and sequence letter in head1.txt
#	Notify Ralph when new versions are installed
#
#  <<ARIZONA-ONLY>>

IPDNUM=ipd286

JDOC=/cs/www/icon/jcon/doc
IPDIR=/cs/www/icon/docs

IPDMAIN=$IPDNUM.htm
SUBD=$IPDIR/$IPDNUM

set -x

#  build files
make

#  copy to Jcon area
rm -f $JDOC/*
cp *.css *.gif *.jpg *.htm $JDOC

#  copy to Icon area (IPD only, images to subdirectory)
#  need to alter links within the main page
rm -f $SUBD/*
cp *.css *.gif *.jpg $SUBD
sed <$IPDMAIN >$IPDIR/$IPDMAIN '
	s!"*jstyle.css"*!"'$IPDNUM'/jstyle.css"!
	s![Ss][Rr][Cc]="*\([a-zA-Z0-9]*\....\)*"*!SRC="'$IPDNUM'/\1"!
'
# workaround netscape directory confusion
cp brnbordr.gif $IPDIR
