#!/bin/sh
#
#  rebuild -- rebuild runtime system if necessary
#
#  (rebuild all .class files if any are out of date;
#   not easily expressed in "make")

JC=${JC-"javac -O"}
BZIP=bin/jcon.zip
ZIP=../$BZIP


if [ -f $ZIP ]; then
    NEWER=`find *.java -newer $ZIP`
else
    NEWER=*.java
fi

if [ "$NEWER" != "" ]; then
    set -e
    echo "+ CLASSPATH=.. $JC *.java"
    CLASSPATH=.. $JC *.java
    echo "+ cd ..; jar cfM $BZIP jcon/*.class"
    cd ..
    jar cfM $BZIP jcon/*.class 2>&1 
fi
