#!/bin/ksh
#
#  upclass file.java -- update .class files that are out of date

JAVAC="toba -K"

if [ `uname` = OSF1 ]; then
    JAVAC="/cs/sumatra/digital/jdk.1.0.2/bin/javac"
    export SYSNAME=alpha_osf32c
fi


FILES=

for FNAME; do
    BASE=${FNAME%.*}
    if [ ! $BASE.java -ot $BASE.class ]; then
	FILES="$FILES $BASE.java"
    fi
done

if [ ${#FILES} = 0 ]; then
    exit 0
fi

set -x 
CLASSPATH=..:$CLASSPATH $JAVAC $FILES
