#!/bin/ksh -p
#
#  upclass file.java -- update .class files that are out of date
#
#  Does not handle transitive dependencies.  If changing one clas
#  requires rebuilding another, run "make clean" and then rebuild.

JAVAC="javac -nowarn -O"
FILES=

for FNAME; do
    BASE=${FNAME%.*}
    if [ ! $BASE.java -ot $BASE.class ]; then
	FILES="$FILES $BASE.java"
    fi
done

if [ ${#FILES} = 0 ]; then
    exit 0
fi

set -x 
CLASSPATH=..:$CLASSPATH $JAVAC $FILES
